version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Buildpack to deploy a war package (install jvm + webapp runner)"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
